DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS DEPARTMENTS;

CREATE TABLE DEPARTMENTS
(
    id   int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    CONSTRAINT departments_pk PRIMARY KEY (id)
);

CREATE TABLE EMPLOYEES
(
    empLogin      varchar(255) NOT NULL,
    name          varchar(255) NOT NULL,
    department_id int4         not null,
    isDepartmentManager boolean not null,
    CONSTRAINT employee_login PRIMARY KEY (empLogin)
);

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT employees_fk FOREIGN KEY (department_id) REFERENCES departments (id) ON UPDATE RESTRICT ON DELETE RESTRICT;